### PR TITLE
Updating gh-pages

### LINKED ISSUE #9: Updating gh-pages branch
The gh-pages branch _still_ says info about sgit, and not forker. Please fix.

### PR DESCRIPTION
**Pull request by monabat79**
Fixes #9.
This update adds an official github-pages page for forker.

### CODE REVIEW

**Comment by Nikitaw99** [comment]
PR is done, awaiting merge.

**Comment by Nikitaw99** [comment]
Deleted CNAME because  I know nothing about ***Your*** current domains.

**Comment by Nikitaw99** [comment]
@phcoder Could you merge this?

**Comment by Nikitaw99** [comment]
I am gonna squash those commits...

**Comment by monabat79** [comment]
Don't merge yet, there is some stuff to fix.

**Pull request closed without merging**
